server-updates:
  file:
    directory-path: ./src/main/resources
    file-name: server-updates.txt
  storage:
    max-size: 20

server:
  servlet:
    context-path: /updatesObserver

spring:
  application:
    name: updates-observer
