server-updates:
  file:
    directory-path: /updates
    file-name: server-updates.txt
  storage:
    max-size: 20

springdoc:
  swagger-ui:
    path: /api-docs.html

server:
  servlet:
    context-path: /api/v1/serverOutageTracker
  port: 8088

spring:
  application:
    name: updates-observer
