server-updates:
  file:
    directory-path: /updates
    file-name: server-updates.txt
  storage:
    max-size: 20

server:
  servlet:
    context-path: /api/v1/serverOutageTracker

spring:
  application:
    name: updates-observer
