server-updates:
  file:
    directory-path: /backup
    file-name: server-outage-backup.txt
  storage:
    max-size: 20

springdoc:
  swagger-ui:
    path: /api-docs.html

server:
  servlet:
    context-path: /api/v1/serverOutageTracker
  port: 8080

spring:
  application:
    name: server-outage-tracker
