version: '3'
services:
  updates-observer:
    image: cooll3r/updates-observer:1.0.0
    container_name: updates-observer
    environment:
      UPDATES_FILE_DIRECTORY_PATH: ${SERVER_UPDATES_FILE_DIRECTORY_PATH}
    volumes:
        - C:\temp:${SERVER_UPDATES_FILE_DIRECTORY_PATH}
    restart: always
    ports:
      - "10000:8080"
